use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PronounForms {
    pub yo: String,
    pub tu: String,
    pub vos: String,
    pub el_ella_usted: String,
    pub nosotros: String,
    pub vosotros: String,
    pub ellos_ellas_ustedes: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ImperativeForms {
    pub tu: String,
    pub vos: String,
    pub usted: String,
    pub nosotros: String,
    pub vosotros: String,
    pub ustedes: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct VerbTable {
    pub infinitive: String,
    pub english: String,
    pub is_irregular: bool,
    pub gerund: String,
    pub participle: String,
    pub present: PronounForms,
    pub preterite: PronounForms,
    pub imperfect: PronounForms,
    pub future: PronounForms,
    pub conditional: PronounForms,
    pub present_subjunctive: PronounForms,
    pub imperfect_subjunctive_ra: PronounForms,
    pub imperfect_subjunctive_se: PronounForms,
    pub imperative_affirmative: ImperativeForms,
    pub imperative_negative: ImperativeForms,
}

pub fn conjugate_verb(infinitive: &str) -> Option<VerbTable> {
    let verb = infinitive.trim().to_lowercase();
    if let Some(table) = get_irregular_verb(&verb) {
        return Some(table);
    }

    // Try regular derivation if ends with ar, er, or ir
    if verb.ends_with("ar") && verb.len() > 2 {
        let stem = &verb[..verb.len() - 2];
        Some(VerbTable {
            infinitive: verb.clone(),
            english: format!("to {}", verb),
            is_irregular: false,
            gerund: format!("{}ando", stem),
            participle: format!("{}ado", stem),
            present: PronounForms {
                yo: format!("{}o", stem),
                tu: format!("{}as", stem),
                vos: format!("{}ás", stem),
                el_ella_usted: format!("{}a", stem),
                nosotros: format!("{}amos", stem),
                vosotros: format!("{}áis", stem),
                ellos_ellas_ustedes: format!("{}an", stem),
            },
            preterite: PronounForms {
                yo: format!("{}é", stem),
                tu: format!("{}aste", stem),
                vos: format!("{}aste", stem),
                el_ella_usted: format!("{}ó", stem),
                nosotros: format!("{}amos", stem),
                vosotros: format!("{}asteis", stem),
                ellos_ellas_ustedes: format!("{}aron", stem),
            },
            imperfect: PronounForms {
                yo: format!("{}aba", stem),
                tu: format!("{}abas", stem),
                vos: format!("{}abas", stem),
                el_ella_usted: format!("{}aba", stem),
                nosotros: format!("{}ábamos", stem),
                vosotros: format!("{}abais", stem),
                ellos_ellas_ustedes: format!("{}aban", stem),
            },
            future: PronounForms {
                yo: format!("{}é", verb),
                tu: format!("{}ás", verb),
                vos: format!("{}ás", verb),
                el_ella_usted: format!("{}á", verb),
                nosotros: format!("{}emos", verb),
                vosotros: format!("{}éis", verb),
                ellos_ellas_ustedes: format!("{}án", verb),
            },
            conditional: PronounForms {
                yo: format!("{}ía", verb),
                tu: format!("{}ías", verb),
                vos: format!("{}ías", verb),
                el_ella_usted: format!("{}ía", verb),
                nosotros: format!("{}íamos", verb),
                vosotros: format!("{}íais", verb),
                ellos_ellas_ustedes: format!("{}ían", verb),
            },
            present_subjunctive: PronounForms {
                yo: format!("{}e", stem),
                tu: format!("{}es", stem),
                vos: format!("{}és", stem),
                el_ella_usted: format!("{}e", stem),
                nosotros: format!("{}emos", stem),
                vosotros: format!("{}éis", stem),
                ellos_ellas_ustedes: format!("{}en", stem),
            },
            imperfect_subjunctive_ra: PronounForms {
                yo: format!("{}ara", stem),
                tu: format!("{}aras", stem),
                vos: format!("{}aras", stem),
                el_ella_usted: format!("{}ara", stem),
                nosotros: format!("{}áramos", stem),
                vosotros: format!("{}arais", stem),
                ellos_ellas_ustedes: format!("{}aran", stem),
            },
            imperfect_subjunctive_se: PronounForms {
                yo: format!("{}ase", stem),
                tu: format!("{}ases", stem),
                vos: format!("{}ases", stem),
                el_ella_usted: format!("{}ase", stem),
                nosotros: format!("{}ásemos", stem),
                vosotros: format!("{}aseis", stem),
                ellos_ellas_ustedes: format!("{}asen", stem),
            },
            imperative_affirmative: ImperativeForms {
                tu: format!("{}a", stem),
                vos: format!("{}á", stem),
                usted: format!("{}e", stem),
                nosotros: format!("{}emos", stem),
                vosotros: format!("{}ad", stem),
                ustedes: format!("{}en", stem),
            },
            imperative_negative: ImperativeForms {
                tu: format!("no {}es", stem),
                vos: format!("no {}és", stem),
                usted: format!("no {}e", stem),
                nosotros: format!("no {}emos", stem),
                vosotros: format!("no {}éis", stem),
                ustedes: format!("no {}en", stem),
            },
        })
    } else if verb.ends_with("er") && verb.len() > 2 {
        let stem = &verb[..verb.len() - 2];
        Some(VerbTable {
            infinitive: verb.clone(),
            english: format!("to {}", verb),
            is_irregular: false,
            gerund: format!("{}iendo", stem),
            participle: format!("{}ido", stem),
            present: PronounForms {
                yo: format!("{}o", stem),
                tu: format!("{}es", stem),
                vos: format!("{}és", stem),
                el_ella_usted: format!("{}e", stem),
                nosotros: format!("{}emos", stem),
                vosotros: format!("{}éis", stem),
                ellos_ellas_ustedes: format!("{}en", stem),
            },
            preterite: PronounForms {
                yo: format!("{}í", stem),
                tu: format!("{}iste", stem),
                vos: format!("{}iste", stem),
                el_ella_usted: format!("{}ió", stem),
                nosotros: format!("{}imos", stem),
                vosotros: format!("{}isteis", stem),
                ellos_ellas_ustedes: format!("{}ieron", stem),
            },
            imperfect: PronounForms {
                yo: format!("{}ía", stem),
                tu: format!("{}ías", stem),
                vos: format!("{}ías", stem),
                el_ella_usted: format!("{}ía", stem),
                nosotros: format!("{}íamos", stem),
                vosotros: format!("{}íais", stem),
                ellos_ellas_ustedes: format!("{}ían", stem),
            },
            future: PronounForms {
                yo: format!("{}é", verb),
                tu: format!("{}ás", verb),
                vos: format!("{}ás", verb),
                el_ella_usted: format!("{}á", verb),
                nosotros: format!("{}emos", verb),
                vosotros: format!("{}éis", verb),
                ellos_ellas_ustedes: format!("{}án", verb),
            },
            conditional: PronounForms {
                yo: format!("{}ía", verb),
                tu: format!("{}ías", verb),
                vos: format!("{}ías", verb),
                el_ella_usted: format!("{}ía", verb),
                nosotros: format!("{}íamos", verb),
                vosotros: format!("{}íais", verb),
                ellos_ellas_ustedes: format!("{}ían", verb),
            },
            present_subjunctive: PronounForms {
                yo: format!("{}a", stem),
                tu: format!("{}as", stem),
                vos: format!("{}ás", stem),
                el_ella_usted: format!("{}a", stem),
                nosotros: format!("{}amos", stem),
                vosotros: format!("{}áis", stem),
                ellos_ellas_ustedes: format!("{}an", stem),
            },
            imperfect_subjunctive_ra: PronounForms {
                yo: format!("{}iera", stem),
                tu: format!("{}ieras", stem),
                vos: format!("{}ieras", stem),
                el_ella_usted: format!("{}iera", stem),
                nosotros: format!("{}iéramos", stem),
                vosotros: format!("{}ierais", stem),
                ellos_ellas_ustedes: format!("{}ieran", stem),
            },
            imperfect_subjunctive_se: PronounForms {
                yo: format!("{}iese", stem),
                tu: format!("{}ieses", stem),
                vos: format!("{}ieses", stem),
                el_ella_usted: format!("{}iese", stem),
                nosotros: format!("{}iésemos", stem),
                vosotros: format!("{}ieseis", stem),
                ellos_ellas_ustedes: format!("{}iesen", stem),
            },
            imperative_affirmative: ImperativeForms {
                tu: format!("{}e", stem),
                vos: format!("{}é", stem),
                usted: format!("{}a", stem),
                nosotros: format!("{}amos", stem),
                vosotros: format!("{}ed", stem),
                ustedes: format!("{}an", stem),
            },
            imperative_negative: ImperativeForms {
                tu: format!("no {}as", stem),
                vos: format!("no {}ás", stem),
                usted: format!("no {}a", stem),
                nosotros: format!("no {}amos", stem),
                vosotros: format!("no {}áis", stem),
                ustedes: format!("no {}an", stem),
            },
        })
    } else if verb.ends_with("ir") && verb.len() > 2 {
        let stem = &verb[..verb.len() - 2];
        Some(VerbTable {
            infinitive: verb.clone(),
            english: format!("to {}", verb),
            is_irregular: false,
            gerund: format!("{}iendo", stem),
            participle: format!("{}ido", stem),
            present: PronounForms {
                yo: format!("{}o", stem),
                tu: format!("{}es", stem),
                vos: format!("{}ís", stem),
                el_ella_usted: format!("{}e", stem),
                nosotros: format!("{}imos", stem),
                vosotros: format!("{}ís", stem),
                ellos_ellas_ustedes: format!("{}en", stem),
            },
            preterite: PronounForms {
                yo: format!("{}í", stem),
                tu: format!("{}iste", stem),
                vos: format!("{}iste", stem),
                el_ella_usted: format!("{}ió", stem),
                nosotros: format!("{}imos", stem),
                vosotros: format!("{}isteis", stem),
                ellos_ellas_ustedes: format!("{}ieron", stem),
            },
            imperfect: PronounForms {
                yo: format!("{}ía", stem),
                tu: format!("{}ías", stem),
                vos: format!("{}ías", stem),
                el_ella_usted: format!("{}ía", stem),
                nosotros: format!("{}íamos", stem),
                vosotros: format!("{}íais", stem),
                ellos_ellas_ustedes: format!("{}ían", stem),
            },
            future: PronounForms {
                yo: format!("{}é", verb),
                tu: format!("{}ás", verb),
                vos: format!("{}ás", verb),
                el_ella_usted: format!("{}á", verb),
                nosotros: format!("{}emos", verb),
                vosotros: format!("{}éis", verb),
                ellos_ellas_ustedes: format!("{}án", verb),
            },
            conditional: PronounForms {
                yo: format!("{}ía", verb),
                tu: format!("{}ías", verb),
                vos: format!("{}ías", verb),
                el_ella_usted: format!("{}ía", verb),
                nosotros: format!("{}íamos", verb),
                vosotros: format!("{}íais", verb),
                ellos_ellas_ustedes: format!("{}ían", verb),
            },
            present_subjunctive: PronounForms {
                yo: format!("{}a", stem),
                tu: format!("{}as", stem),
                vos: format!("{}ás", stem),
                el_ella_usted: format!("{}a", stem),
                nosotros: format!("{}amos", stem),
                vosotros: format!("{}áis", stem),
                ellos_ellas_ustedes: format!("{}an", stem),
            },
            imperfect_subjunctive_ra: PronounForms {
                yo: format!("{}iera", stem),
                tu: format!("{}ieras", stem),
                vos: format!("{}ieras", stem),
                el_ella_usted: format!("{}iera", stem),
                nosotros: format!("{}iéramos", stem),
                vosotros: format!("{}ierais", stem),
                ellos_ellas_ustedes: format!("{}ieran", stem),
            },
            imperfect_subjunctive_se: PronounForms {
                yo: format!("{}iese", stem),
                tu: format!("{}ieses", stem),
                vos: format!("{}ieses", stem),
                el_ella_usted: format!("{}iese", stem),
                nosotros: format!("{}iésemos", stem),
                vosotros: format!("{}ieseis", stem),
                ellos_ellas_ustedes: format!("{}iesen", stem),
            },
            imperative_affirmative: ImperativeForms {
                tu: format!("{}e", stem),
                vos: format!("{}í", stem),
                usted: format!("{}a", stem),
                nosotros: format!("{}amos", stem),
                vosotros: format!("{}id", stem),
                ustedes: format!("{}an", stem),
            },
            imperative_negative: ImperativeForms {
                tu: format!("no {}as", stem),
                vos: format!("no {}ás", stem),
                usted: format!("no {}a", stem),
                nosotros: format!("no {}amos", stem),
                vosotros: format!("no {}áis", stem),
                ustedes: format!("no {}an", stem),
            },
        })
    } else {
        None
    }
}

fn get_irregular_verb(verb: &str) -> Option<VerbTable> {
    match verb {
        "ser" => Some(VerbTable {
            infinitive: "ser".to_string(),
            english: "to be (essential/permanent)".to_string(),
            is_irregular: true,
            gerund: "siendo".to_string(),
            participle: "sido".to_string(),
            present: PronounForms {
                yo: "soy".to_string(),
                tu: "eres".to_string(),
                vos: "sos".to_string(),
                el_ella_usted: "es".to_string(),
                nosotros: "somos".to_string(),
                vosotros: "sois".to_string(),
                ellos_ellas_ustedes: "son".to_string(),
            },
            preterite: PronounForms {
                yo: "fui".to_string(),
                tu: "fuiste".to_string(),
                vos: "fuiste".to_string(),
                el_ella_usted: "fue".to_string(),
                nosotros: "fuimos".to_string(),
                vosotros: "fuisteis".to_string(),
                ellos_ellas_ustedes: "fueron".to_string(),
            },
            imperfect: PronounForms {
                yo: "era".to_string(),
                tu: "eras".to_string(),
                vos: "eras".to_string(),
                el_ella_usted: "era".to_string(),
                nosotros: "éramos".to_string(),
                vosotros: "erais".to_string(),
                ellos_ellas_ustedes: "eran".to_string(),
            },
            future: PronounForms {
                yo: "seré".to_string(),
                tu: "serás".to_string(),
                vos: "serás".to_string(),
                el_ella_usted: "será".to_string(),
                nosotros: "seremos".to_string(),
                vosotros: "seréis".to_string(),
                ellos_ellas_ustedes: "serán".to_string(),
            },
            conditional: PronounForms {
                yo: "sería".to_string(),
                tu: "serías".to_string(),
                vos: "serías".to_string(),
                el_ella_usted: "sería".to_string(),
                nosotros: "seríamos".to_string(),
                vosotros: "seríais".to_string(),
                ellos_ellas_ustedes: "serían".to_string(),
            },
            present_subjunctive: PronounForms {
                yo: "sea".to_string(),
                tu: "seas".to_string(),
                vos: "seas".to_string(),
                el_ella_usted: "sea".to_string(),
                nosotros: "seamos".to_string(),
                vosotros: "seáis".to_string(),
                ellos_ellas_ustedes: "sean".to_string(),
            },
            imperfect_subjunctive_ra: PronounForms {
                yo: "fuera".to_string(),
                tu: "fueras".to_string(),
                vos: "fueras".to_string(),
                el_ella_usted: "fuera".to_string(),
                nosotros: "fuéramos".to_string(),
                vosotros: "fuerais".to_string(),
                ellos_ellas_ustedes: "fueran".to_string(),
            },
            imperfect_subjunctive_se: PronounForms {
                yo: "fuese".to_string(),
                tu: "fueses".to_string(),
                vos: "fueses".to_string(),
                el_ella_usted: "fuese".to_string(),
                nosotros: "fuésemos".to_string(),
                vosotros: "fueseis".to_string(),
                ellos_ellas_ustedes: "fuesen".to_string(),
            },
            imperative_affirmative: ImperativeForms {
                tu: "sé".to_string(),
                vos: "sé".to_string(),
                usted: "sea".to_string(),
                nosotros: "seamos".to_string(),
                vosotros: "sed".to_string(),
                ustedes: "sean".to_string(),
            },
            imperative_negative: ImperativeForms {
                tu: "no seas".to_string(),
                vos: "no seas".to_string(),
                usted: "no sea".to_string(),
                nosotros: "no seamos".to_string(),
                vosotros: "no seáis".to_string(),
                ustedes: "no sean".to_string(),
            },
        }),
        "estar" => Some(VerbTable {
            infinitive: "estar".to_string(),
            english: "to be (state/location)".to_string(),
            is_irregular: true,
            gerund: "estando".to_string(),
            participle: "estado".to_string(),
            present: PronounForms {
                yo: "estoy".to_string(),
                tu: "estás".to_string(),
                vos: "estás".to_string(),
                el_ella_usted: "está".to_string(),
                nosotros: "estamos".to_string(),
                vosotros: "estáis".to_string(),
                ellos_ellas_ustedes: "están".to_string(),
            },
            preterite: PronounForms {
                yo: "estuve".to_string(),
                tu: "estuviste".to_string(),
                vos: "estuviste".to_string(),
                el_ella_usted: "estuvo".to_string(),
                nosotros: "estuvimos".to_string(),
                vosotros: "estuvisteis".to_string(),
                ellos_ellas_ustedes: "estuvieron".to_string(),
            },
            imperfect: PronounForms {
                yo: "estaba".to_string(),
                tu: "estabas".to_string(),
                vos: "estabas".to_string(),
                el_ella_usted: "estaba".to_string(),
                nosotros: "estábamos".to_string(),
                vosotros: "estabais".to_string(),
                ellos_ellas_ustedes: "estaban".to_string(),
            },
            future: PronounForms {
                yo: "estaré".to_string(),
                tu: "estarás".to_string(),
                vos: "estarás".to_string(),
                el_ella_usted: "estará".to_string(),
                nosotros: "estaremos".to_string(),
                vosotros: "estaréis".to_string(),
                ellos_ellas_ustedes: "estarán".to_string(),
            },
            conditional: PronounForms {
                yo: "estaría".to_string(),
                tu: "estarías".to_string(),
                vos: "estarías".to_string(),
                el_ella_usted: "estaría".to_string(),
                nosotros: "estaríamos".to_string(),
                vosotros: "estaríais".to_string(),
                ellos_ellas_ustedes: "estarían".to_string(),
            },
            present_subjunctive: PronounForms {
                yo: "esté".to_string(),
                tu: "estés".to_string(),
                vos: "estés".to_string(),
                el_ella_usted: "esté".to_string(),
                nosotros: "estemos".to_string(),
                vosotros: "estéis".to_string(),
                ellos_ellas_ustedes: "estén".to_string(),
            },
            imperfect_subjunctive_ra: PronounForms {
                yo: "estuviera".to_string(),
                tu: "estuvieras".to_string(),
                vos: "estuvieras".to_string(),
                el_ella_usted: "estuviera".to_string(),
                nosotros: "estuviéramos".to_string(),
                vosotros: "estuvierais".to_string(),
                ellos_ellas_ustedes: "estuvieran".to_string(),
            },
            imperfect_subjunctive_se: PronounForms {
                yo: "estuviese".to_string(),
                tu: "estuvieses".to_string(),
                vos: "estuvieses".to_string(),
                el_ella_usted: "estuviese".to_string(),
                nosotros: "estuviésemos".to_string(),
                vosotros: "estuvieseis".to_string(),
                ellos_ellas_ustedes: "estuviesen".to_string(),
            },
            imperative_affirmative: ImperativeForms {
                tu: "está".to_string(),
                vos: "estate".to_string(),
                usted: "esté".to_string(),
                nosotros: "estemos".to_string(),
                vosotros: "estad".to_string(),
                ustedes: "estén".to_string(),
            },
            imperative_negative: ImperativeForms {
                tu: "no estés".to_string(),
                vos: "no estés".to_string(),
                usted: "no esté".to_string(),
                nosotros: "no estemos".to_string(),
                vosotros: "no estéis".to_string(),
                ustedes: "no estén".to_string(),
            },
        }),
        "haber" => Some(VerbTable {
            infinitive: "haber".to_string(),
            english: "to have (auxiliary/existential)".to_string(),
            is_irregular: true,
            gerund: "habiendo".to_string(),
            participle: "habido".to_string(),
            present: PronounForms {
                yo: "he".to_string(),
                tu: "has".to_string(),
                vos: "has".to_string(),
                el_ella_usted: "ha / hay".to_string(),
                nosotros: "hemos".to_string(),
                vosotros: "habéis".to_string(),
                ellos_ellas_ustedes: "han".to_string(),
            },
            preterite: PronounForms {
                yo: "hube".to_string(),
                tu: "hubiste".to_string(),
                vos: "hubiste".to_string(),
                el_ella_usted: "hubo".to_string(),
                nosotros: "hubimos".to_string(),
                vosotros: "hubisteis".to_string(),
                ellos_ellas_ustedes: "hubieron".to_string(),
            },
            imperfect: PronounForms {
                yo: "había".to_string(),
                tu: "habías".to_string(),
                vos: "habías".to_string(),
                el_ella_usted: "había".to_string(),
                nosotros: "habíamos".to_string(),
                vosotros: "habíais".to_string(),
                ellos_ellas_ustedes: "habían".to_string(),
            },
            future: PronounForms {
                yo: "habré".to_string(),
                tu: "habrás".to_string(),
                vos: "habrás".to_string(),
                el_ella_usted: "habrá".to_string(),
                nosotros: "habremos".to_string(),
                vosotros: "habréis".to_string(),
                ellos_ellas_ustedes: "habrán".to_string(),
            },
            conditional: PronounForms {
                yo: "habría".to_string(),
                tu: "habrías".to_string(),
                vos: "habrías".to_string(),
                el_ella_usted: "habría".to_string(),
                nosotros: "habríamos".to_string(),
                vosotros: "habríais".to_string(),
                ellos_ellas_ustedes: "habrían".to_string(),
            },
            present_subjunctive: PronounForms {
                yo: "haya".to_string(),
                tu: "hayas".to_string(),
                vos: "hayas".to_string(),
                el_ella_usted: "haya".to_string(),
                nosotros: "hayamos".to_string(),
                vosotros: "hayáis".to_string(),
                ellos_ellas_ustedes: "hayan".to_string(),
            },
            imperfect_subjunctive_ra: PronounForms {
                yo: "hubiera".to_string(),
                tu: "hubieras".to_string(),
                vos: "hubieras".to_string(),
                el_ella_usted: "hubiera".to_string(),
                nosotros: "hubiéramos".to_string(),
                vosotros: "hubierais".to_string(),
                ellos_ellas_ustedes: "hubieran".to_string(),
            },
            imperfect_subjunctive_se: PronounForms {
                yo: "hubiese".to_string(),
                tu: "hubieses".to_string(),
                vos: "hubieses".to_string(),
                el_ella_usted: "hubiese".to_string(),
                nosotros: "hubiésemos".to_string(),
                vosotros: "hubieseis".to_string(),
                ellos_ellas_ustedes: "hubiesen".to_string(),
            },
            imperative_affirmative: ImperativeForms {
                tu: "he".to_string(),
                vos: "habé".to_string(),
                usted: "haya".to_string(),
                nosotros: "hayamos".to_string(),
                vosotros: "habed".to_string(),
                ustedes: "hayan".to_string(),
            },
            imperative_negative: ImperativeForms {
                tu: "no hayas".to_string(),
                vos: "no hayas".to_string(),
                usted: "no haya".to_string(),
                nosotros: "no hayamos".to_string(),
                vosotros: "no hayáis".to_string(),
                ustedes: "no hayan".to_string(),
            },
        }),
        "tener" => Some(VerbTable {
            infinitive: "tener".to_string(),
            english: "to have (possession)".to_string(),
            is_irregular: true,
            gerund: "teniendo".to_string(),
            participle: "tenido".to_string(),
            present: PronounForms {
                yo: "tengo".to_string(),
                tu: "tienes".to_string(),
                vos: "tenés".to_string(),
                el_ella_usted: "tiene".to_string(),
                nosotros: "tenemos".to_string(),
                vosotros: "tenéis".to_string(),
                ellos_ellas_ustedes: "tienen".to_string(),
            },
            preterite: PronounForms {
                yo: "tuve".to_string(),
                tu: "tuviste".to_string(),
                vos: "tuviste".to_string(),
                el_ella_usted: "tuvo".to_string(),
                nosotros: "tuvimos".to_string(),
                vosotros: "tuvisteis".to_string(),
                ellos_ellas_ustedes: "tuvieron".to_string(),
            },
            imperfect: PronounForms {
                yo: "tenía".to_string(),
                tu: "tenías".to_string(),
                vos: "tenías".to_string(),
                el_ella_usted: "tenía".to_string(),
                nosotros: "teníamos".to_string(),
                vosotros: "teníais".to_string(),
                ellos_ellas_ustedes: "tenían".to_string(),
            },
            future: PronounForms {
                yo: "tendré".to_string(),
                tu: "tendrás".to_string(),
                vos: "tendrás".to_string(),
                el_ella_usted: "tendrá".to_string(),
                nosotros: "tendremos".to_string(),
                vosotros: "tendréis".to_string(),
                ellos_ellas_ustedes: "tendrán".to_string(),
            },
            conditional: PronounForms {
                yo: "tendría".to_string(),
                tu: "tendrías".to_string(),
                vos: "tendrías".to_string(),
                el_ella_usted: "tendría".to_string(),
                nosotros: "tendríamos".to_string(),
                vosotros: "tendríais".to_string(),
                ellos_ellas_ustedes: "tendrían".to_string(),
            },
            present_subjunctive: PronounForms {
                yo: "tenga".to_string(),
                tu: "tengas".to_string(),
                vos: "tengas".to_string(),
                el_ella_usted: "tenga".to_string(),
                nosotros: "tengamos".to_string(),
                vosotros: "tengáis".to_string(),
                ellos_ellas_ustedes: "tengan".to_string(),
            },
            imperfect_subjunctive_ra: PronounForms {
                yo: "tuviera".to_string(),
                tu: "tuvieras".to_string(),
                vos: "tuvieras".to_string(),
                el_ella_usted: "tuviera".to_string(),
                nosotros: "tuviéramos".to_string(),
                vosotros: "tuvierais".to_string(),
                ellos_ellas_ustedes: "tuvieran".to_string(),
            },
            imperfect_subjunctive_se: PronounForms {
                yo: "tuviese".to_string(),
                tu: "tuvieses".to_string(),
                vos: "tuvieses".to_string(),
                el_ella_usted: "tuviese".to_string(),
                nosotros: "tuviésemos".to_string(),
                vosotros: "tuvieseis".to_string(),
                ellos_ellas_ustedes: "tuviesen".to_string(),
            },
            imperative_affirmative: ImperativeForms {
                tu: "ten".to_string(),
                vos: "tené".to_string(),
                usted: "tenga".to_string(),
                nosotros: "tengamos".to_string(),
                vosotros: "tened".to_string(),
                ustedes: "tengan".to_string(),
            },
            imperative_negative: ImperativeForms {
                tu: "no tengas".to_string(),
                vos: "no tengas".to_string(),
                usted: "no tenga".to_string(),
                nosotros: "no tengamos".to_string(),
                vosotros: "no tengáis".to_string(),
                ustedes: "no tengan".to_string(),
            },
        }),
        "hacer" => Some(VerbTable {
            infinitive: "hacer".to_string(),
            english: "to do / make".to_string(),
            is_irregular: true,
            gerund: "haciendo".to_string(),
            participle: "hecho".to_string(),
            present: PronounForms {
                yo: "hago".to_string(),
                tu: "haces".to_string(),
                vos: "hacés".to_string(),
                el_ella_usted: "hace".to_string(),
                nosotros: "hacemos".to_string(),
                vosotros: "hacéis".to_string(),
                ellos_ellas_ustedes: "hacen".to_string(),
            },
            preterite: PronounForms {
                yo: "hice".to_string(),
                tu: "hiciste".to_string(),
                vos: "hiciste".to_string(),
                el_ella_usted: "hizo".to_string(),
                nosotros: "hicimos".to_string(),
                vosotros: "hicisteis".to_string(),
                ellos_ellas_ustedes: "hicieron".to_string(),
            },
            imperfect: PronounForms {
                yo: "hacía".to_string(),
                tu: "hacías".to_string(),
                vos: "hacías".to_string(),
                el_ella_usted: "hacía".to_string(),
                nosotros: "hacíamos".to_string(),
                vosotros: "hacíais".to_string(),
                ellos_ellas_ustedes: "hacían".to_string(),
            },
            future: PronounForms {
                yo: "haré".to_string(),
                tu: "harás".to_string(),
                vos: "harás".to_string(),
                el_ella_usted: "hará".to_string(),
                nosotros: "haremos".to_string(),
                vosotros: "haréis".to_string(),
                ellos_ellas_ustedes: "harán".to_string(),
            },
            conditional: PronounForms {
                yo: "haría".to_string(),
                tu: "harías".to_string(),
                vos: "harías".to_string(),
                el_ella_usted: "haría".to_string(),
                nosotros: "haríamos".to_string(),
                vosotros: "haríais".to_string(),
                ellos_ellas_ustedes: "harían".to_string(),
            },
            present_subjunctive: PronounForms {
                yo: "haga".to_string(),
                tu: "hagas".to_string(),
                vos: "hagas".to_string(),
                el_ella_usted: "haga".to_string(),
                nosotros: "hagamos".to_string(),
                vosotros: "hagáis".to_string(),
                ellos_ellas_ustedes: "hagan".to_string(),
            },
            imperfect_subjunctive_ra: PronounForms {
                yo: "hiciera".to_string(),
                tu: "hicieras".to_string(),
                vos: "hicieras".to_string(),
                el_ella_usted: "hiciera".to_string(),
                nosotros: "hiciéramos".to_string(),
                vosotros: "hicierais".to_string(),
                ellos_ellas_ustedes: "hicieran".to_string(),
            },
            imperfect_subjunctive_se: PronounForms {
                yo: "hiciese".to_string(),
                tu: "hicieses".to_string(),
                vos: "hicieses".to_string(),
                el_ella_usted: "hiciese".to_string(),
                nosotros: "hiciésemos".to_string(),
                vosotros: "hieseis".to_string(),
                ellos_ellas_ustedes: "hiciesen".to_string(),
            },
            imperative_affirmative: ImperativeForms {
                tu: "haz".to_string(),
                vos: "hacé".to_string(),
                usted: "haga".to_string(),
                nosotros: "hagamos".to_string(),
                vosotros: "haced".to_string(),
                ustedes: "hagan".to_string(),
            },
            imperative_negative: ImperativeForms {
                tu: "no hagas".to_string(),
                vos: "no hagas".to_string(),
                usted: "no haga".to_string(),
                nosotros: "no hagamos".to_string(),
                vosotros: "no hagáis".to_string(),
                ustedes: "no hagan".to_string(),
            },
        }),
        "ir" => Some(VerbTable {
            infinitive: "ir".to_string(),
            english: "to go".to_string(),
            is_irregular: true,
            gerund: "yendo".to_string(),
            participle: "ido".to_string(),
            present: PronounForms {
                yo: "voy".to_string(),
                tu: "vas".to_string(),
                vos: "vas".to_string(),
                el_ella_usted: "va".to_string(),
                nosotros: "vamos".to_string(),
                vosotros: "vais".to_string(),
                ellos_ellas_ustedes: "van".to_string(),
            },
            preterite: PronounForms {
                yo: "fui".to_string(),
                tu: "fuiste".to_string(),
                vos: "fuiste".to_string(),
                el_ella_usted: "fue".to_string(),
                nosotros: "fuimos".to_string(),
                vosotros: "fuisteis".to_string(),
                ellos_ellas_ustedes: "fueron".to_string(),
            },
            imperfect: PronounForms {
                yo: "iba".to_string(),
                tu: "ibas".to_string(),
                vos: "ibas".to_string(),
                el_ella_usted: "iba".to_string(),
                nosotros: "íbamos".to_string(),
                vosotros: "ibais".to_string(),
                ellos_ellas_ustedes: "iban".to_string(),
            },
            future: PronounForms {
                yo: "iré".to_string(),
                tu: "irás".to_string(),
                vos: "irás".to_string(),
                el_ella_usted: "irá".to_string(),
                nosotros: "iremos".to_string(),
                vosotros: "iréis".to_string(),
                ellos_ellas_ustedes: "irán".to_string(),
            },
            conditional: PronounForms {
                yo: "iría".to_string(),
                tu: "irías".to_string(),
                vos: "irías".to_string(),
                el_ella_usted: "iría".to_string(),
                nosotros: "iríamos".to_string(),
                vosotros: "iríais".to_string(),
                ellos_ellas_ustedes: "irían".to_string(),
            },
            present_subjunctive: PronounForms {
                yo: "vaya".to_string(),
                tu: "vayas".to_string(),
                vos: "vayas".to_string(),
                el_ella_usted: "vaya".to_string(),
                nosotros: "vayamos".to_string(),
                vosotros: "vayáis".to_string(),
                ellos_ellas_ustedes: "vayan".to_string(),
            },
            imperfect_subjunctive_ra: PronounForms {
                yo: "fuera".to_string(),
                tu: "fueras".to_string(),
                vos: "fueras".to_string(),
                el_ella_usted: "fuera".to_string(),
                nosotros: "fuéramos".to_string(),
                vosotros: "fuerais".to_string(),
                ellos_ellas_ustedes: "fueran".to_string(),
            },
            imperfect_subjunctive_se: PronounForms {
                yo: "fuese".to_string(),
                tu: "fueses".to_string(),
                vos: "fueses".to_string(),
                el_ella_usted: "fuese".to_string(),
                nosotros: "fuésemos".to_string(),
                vosotros: "fueseis".to_string(),
                ellos_ellas_ustedes: "fuesen".to_string(),
            },
            imperative_affirmative: ImperativeForms {
                tu: "ve".to_string(),
                vos: "andá".to_string(),
                usted: "vaya".to_string(),
                nosotros: "vamos / vayamos".to_string(),
                vosotros: "id".to_string(),
                ustedes: "vayan".to_string(),
            },
            imperative_negative: ImperativeForms {
                tu: "no vayas".to_string(),
                vos: "no vayas".to_string(),
                usted: "no vaya".to_string(),
                nosotros: "no vayamos".to_string(),
                vosotros: "no vayáis".to_string(),
                ustedes: "no vayan".to_string(),
            },
        }),
        "poder" => Some(VerbTable {
            infinitive: "poder".to_string(),
            english: "to be able to / can".to_string(),
            is_irregular: true,
            gerund: "pudiendo".to_string(),
            participle: "podido".to_string(),
            present: PronounForms {
                yo: "puedo".to_string(),
                tu: "puedes".to_string(),
                vos: "podés".to_string(),
                el_ella_usted: "puede".to_string(),
                nosotros: "podemos".to_string(),
                vosotros: "podéis".to_string(),
                ellos_ellas_ustedes: "pueden".to_string(),
            },
            preterite: PronounForms {
                yo: "pude".to_string(),
                tu: "pudiste".to_string(),
                vos: "pudiste".to_string(),
                el_ella_usted: "pudo".to_string(),
                nosotros: "pudimos".to_string(),
                vosotros: "pudisteis".to_string(),
                ellos_ellas_ustedes: "pudieron".to_string(),
            },
            imperfect: PronounForms {
                yo: "podía".to_string(),
                tu: "podías".to_string(),
                vos: "podías".to_string(),
                el_ella_usted: "podía".to_string(),
                nosotros: "podíamos".to_string(),
                vosotros: "podíais".to_string(),
                ellos_ellas_ustedes: "podían".to_string(),
            },
            future: PronounForms {
                yo: "podré".to_string(),
                tu: "podrás".to_string(),
                vos: "podrás".to_string(),
                el_ella_usted: "podrá".to_string(),
                nosotros: "podremos".to_string(),
                vosotros: "podréis".to_string(),
                ellos_ellas_ustedes: "podrán".to_string(),
            },
            conditional: PronounForms {
                yo: "podría".to_string(),
                tu: "podrías".to_string(),
                vos: "podrías".to_string(),
                el_ella_usted: "podría".to_string(),
                nosotros: "podríamos".to_string(),
                vosotros: "podríais".to_string(),
                ellos_ellas_ustedes: "podrían".to_string(),
            },
            present_subjunctive: PronounForms {
                yo: "pueda".to_string(),
                tu: "puedas".to_string(),
                vos: "puedas".to_string(),
                el_ella_usted: "pueda".to_string(),
                nosotros: "podamos".to_string(),
                vosotros: "podáis".to_string(),
                ellos_ellas_ustedes: "puedan".to_string(),
            },
            imperfect_subjunctive_ra: PronounForms {
                yo: "pudiera".to_string(),
                tu: "pudieras".to_string(),
                vos: "pudieras".to_string(),
                el_ella_usted: "pudiera".to_string(),
                nosotros: "pudiéramos".to_string(),
                vosotros: "pudierais".to_string(),
                ellos_ellas_ustedes: "pudieran".to_string(),
            },
            imperfect_subjunctive_se: PronounForms {
                yo: "pudiese".to_string(),
                tu: "pudieses".to_string(),
                vos: "pudieses".to_string(),
                el_ella_usted: "pudiese".to_string(),
                nosotros: "pudiésemos".to_string(),
                vosotros: "pudieseis".to_string(),
                ellos_ellas_ustedes: "pudiesen".to_string(),
            },
            imperative_affirmative: ImperativeForms {
                tu: "puede".to_string(),
                vos: "podé".to_string(),
                usted: "pueda".to_string(),
                nosotros: "podamos".to_string(),
                vosotros: "poded".to_string(),
                ustedes: "puedan".to_string(),
            },
            imperative_negative: ImperativeForms {
                tu: "no puedas".to_string(),
                vos: "no puedas".to_string(),
                usted: "no pueda".to_string(),
                nosotros: "no podamos".to_string(),
                vosotros: "no podáis".to_string(),
                ustedes: "no puedan".to_string(),
            },
        }),
        "decir" => Some(VerbTable {
            infinitive: "decir".to_string(),
            english: "to say / tell".to_string(),
            is_irregular: true,
            gerund: "diciendo".to_string(),
            participle: "dicho".to_string(),
            present: PronounForms {
                yo: "digo".to_string(),
                tu: "dices".to_string(),
                vos: "decís".to_string(),
                el_ella_usted: "dice".to_string(),
                nosotros: "decimos".to_string(),
                vosotros: "decís".to_string(),
                ellos_ellas_ustedes: "dicen".to_string(),
            },
            preterite: PronounForms {
                yo: "dije".to_string(),
                tu: "dijiste".to_string(),
                vos: "dijiste".to_string(),
                el_ella_usted: "dijo".to_string(),
                nosotros: "dijimos".to_string(),
                vosotros: "dijisteis".to_string(),
                ellos_ellas_ustedes: "dijeron".to_string(),
            },
            imperfect: PronounForms {
                yo: "decía".to_string(),
                tu: "decías".to_string(),
                vos: "decías".to_string(),
                el_ella_usted: "decía".to_string(),
                nosotros: "decíamos".to_string(),
                vosotros: "decíais".to_string(),
                ellos_ellas_ustedes: "decían".to_string(),
            },
            future: PronounForms {
                yo: "diré".to_string(),
                tu: "dirás".to_string(),
                vos: "dirás".to_string(),
                el_ella_usted: "dirá".to_string(),
                nosotros: "diremos".to_string(),
                vosotros: "diréis".to_string(),
                ellos_ellas_ustedes: "dirán".to_string(),
            },
            conditional: PronounForms {
                yo: "diría".to_string(),
                tu: "dirías".to_string(),
                vos: "dirías".to_string(),
                el_ella_usted: "diría".to_string(),
                nosotros: "diríamos".to_string(),
                vosotros: "diríais".to_string(),
                ellos_ellas_ustedes: "dirían".to_string(),
            },
            present_subjunctive: PronounForms {
                yo: "diga".to_string(),
                tu: "digas".to_string(),
                vos: "digas".to_string(),
                el_ella_usted: "diga".to_string(),
                nosotros: "digamos".to_string(),
                vosotros: "digáis".to_string(),
                ellos_ellas_ustedes: "digan".to_string(),
            },
            imperfect_subjunctive_ra: PronounForms {
                yo: "dijera".to_string(),
                tu: "dijeras".to_string(),
                vos: "dijeras".to_string(),
                el_ella_usted: "dijera".to_string(),
                nosotros: "dijéramos".to_string(),
                vosotros: "dijerais".to_string(),
                ellos_ellas_ustedes: "dijeran".to_string(),
            },
            imperfect_subjunctive_se: PronounForms {
                yo: "dijese".to_string(),
                tu: "dijeses".to_string(),
                vos: "dijeses".to_string(),
                el_ella_usted: "dijese".to_string(),
                nosotros: "dijésemos".to_string(),
                vosotros: "dijeseis".to_string(),
                ellos_ellas_ustedes: "dijesen".to_string(),
            },
            imperative_affirmative: ImperativeForms {
                tu: "di".to_string(),
                vos: "decí".to_string(),
                usted: "diga".to_string(),
                nosotros: "digamos".to_string(),
                vosotros: "decid".to_string(),
                ustedes: "digan".to_string(),
            },
            imperative_negative: ImperativeForms {
                tu: "no digas".to_string(),
                vos: "no digas".to_string(),
                usted: "no diga".to_string(),
                nosotros: "no digamos".to_string(),
                vosotros: "no digáis".to_string(),
                ustedes: "no digan".to_string(),
            },
        }),
        _ => None,
    }
}
